### ISSUE TITLE
flutter_secure_storage_linux/linux/flutter_secure_storage_linux_plugin.cc:193:50: error: use of undeclared identifier 'APPLICATION_ID'

### ISSUE THREAD

**Issue by pfchen** [juliansteenbakker/flutter_secure_storage#829]
It seems that [flutter_secure_storage_linux/linux/CMakeLists.txt](https://github.com/juliansteenbakker/flutter_secure_storage/blob/develop/flutter_secure_storage_linux/linux/CMakeLists.txt) does not include the `APPLICATION_ID` flag.  

It can be fixed with:
```
add_definitions(-DAPPLICATION_ID="${APPLICATION_ID}")
```

**Comment by dayeguilaiye** [comment]
I found the same problem, any progress? Or did you find any workaround @pfchen? Thanks a lot

**Comment by doreille** [comment]
I also have the same problem on flutter 3.27.1. The proposed solution solves the problem. Could the change be included in version 10.0.0 in preparation?

**Comment by juliansteenbakker** [comment]
This is added in v9.2.4. Please let me know if there are any other issues.

**Comment by doreille** [comment]
Just in case you missed it, the fix is not yet in pub.dev (https://pub.dev/packages/flutter_secure_storage_linux/versions). You certainly need to increase the version number of flutter_secure_storage_linux.

However, if you refer directly to the master branch of github, the problem is solved.

**Comment by SnoozeFreddo** [comment]
+1,
It's not in v9.2.4

**Comment by AQMpolyface** [comment]
+1

Also get the error in 9.2.4

**Comment by AQMpolyface** [comment]
but it worked when adding both version to dependencies
  flutter_secure_storage: ^4.2.1
  flutter_secure_storage_linux: ^2.0.1

**Comment by nns52k** [comment]
flutter_secure_storage_linux-2.0.1 is fixed but flutter_secure_storage-9.2.4 doesn't use it. Instead, flutter_secure_storage-9.2.4 still uses flutter_secure_storage_linux-1.2.2 as one of its dependencies. flutter_secure_storage_linux-1.2.2 is the one that causes this `APPLICATION_ID` problem.

**Comment by mbnoimi** [comment]
still occurs with
- flutter_secure_storage: ^9.2.4
- Flutter 3.29.2

**Comment by mbnoimi** [comment]
I wonder why this issue still closed although many users reported it (I found many users confirmed it over the web)?!

**Comment by kq1231** [comment]
Yeah I'm also facing the same issue.

**Comment by ClemsRocket** [comment]
@juliansteenbakker It looks like you closed this as completed but the issue is still present in v9.2.4, as said before we need the versioning issue fixed (depend on flutter_secure_storage_linux:2.0.1) , could this issue be reopened?

**Comment by juliansteenbakker** [comment]
I'm sorry for the delay. I have lots and lots of mail/issues assigned to me, and was focussing on another plugin for the past 2 months. I am going to continue my work on this package the upcoming days.

It was released in v10.0.0-beta.4, not in 9.2.4. I'm working on a new version.

**Comment by juliansteenbakker** [comment]
I have released `v1.2.3` of the linux plugin. If you run `flutter pub upgrade` it should automatically upgrade the plugin to the latest version. Once again sorry about the delay.

**Comment by stdNullPtr** [comment]
@juliansteenbakker Hi, I had just added flutter_secure_storage: ^4.2.1 to my project and it seems I am facing this issue 
`/linux/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage/linux/flutter_secure_storage_plugin.cc:142:50: error: use of undeclared identifier 'APPLICATION_ID'`
