### ISSUE TITLE
Delete: Keys are not being deleted in iOS

### ISSUE THREAD

**Issue by amritnew** [juliansteenbakker/flutter_secure_storage#849]
```
flutterSecureStorage.delete(key: key)
```
No exception is being thrown; however, the key still exists in iOS. Even after calling delete, my app can still retrieve the key.
```
await flutterSecureStorage.read(key: key)
```

PS: This issue exists inthe  new version `9.2.3`, this issue doesn't exist in `9.2.2`.
Quick Fix is to downgrade the version to `9.2.2`.

**Comment by juliansteenbakker** [comment]
Hi, i have tested this with the example app with v9.2.3, but i can't reproduce this. Can you share which ios options you use?

**Comment by matteoscaramuzza** [comment]
Same for me. I use this config:

```
const options = IOSOptions(
    accessibility: KeychainAccessibility.first_unlock,
    accountName: "myapp_secure_storage_service",
    synchronizable: true);
```

**Comment by maplepam** [comment]
We encountered this as well

**Comment by juliansteenbakker** [comment]
Are you sure the options are added to every call? The only way i can reproduce this if i add the options to every call except for `delete` or `deleteAll`. Is it possible to provide some sample code in which you are able to reproduce this?

**Comment by matteoscaramuzza** [comment]
I declare the secure storage like this:

```
file: 'package:myapp/helpers/secure_storage/fl_secure_storage.dart';

const _androidOptions = AndroidOptions(resetOnError: true);
const options = IOSOptions(
    accessibility: KeychainAccessibility.first_unlock,
    accountName: "myapp_secure_storage_service",
    synchronizable: true);

const flSecureStorage =
    FlutterSecureStorage(aOptions: _androidOptions, iOptions: options);
```

and then I import `flSecureStorage` in every file where i need it .

```
import 'package:myapp/helpers/secure_storage/secure_storage_keys.dart';
import 'package:myapp/helpers/secure_storage/fl_secure_storage.dart';

 Future<void> myMethod() async {
    await flSecureStorage.delete(key: SecureStorageKeys.accessToken);
 }
```

**Comment by juliansteenbakker** [comment]
I have found the issue, which is the parameter `synchornisable` and `accessibility` were not passed to `delete` and `deleteAll`.

**Comment by juliansteenbakker** [comment]
I have released v9.2.4 with this fix. Please let me know if there are any other issues.

**Comment by fromlabs** [comment]
I still have the problem with `deleteAll()` in v9.2.4 (v9.2.2 it's OK). 
I have this configuration:
```
FlutterSecureStorage(
  iOptions: IOSOptions(
      accessibility: KeychainAccessibility.first_unlock_this_device,
      synchronizable: true))
```

**Comment by juliansteenbakker** [comment]
are you sure you did not specify any iOptions to `deleteAll`, but only in the constructor? Also, can you reproduce this with the example app, or do you have any other code so i can try and reproduce it?

Also, please make sure to run `flutter clean` after upgrading the package.
