### ISSUE TITLE
PlatformException (PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT

### ISSUE THREAD

**Issue by SteveJosephh21** [juliansteenbakker/flutter_secure_storage#871]
Hi,
I have used secure storage plugin flutter_secure_storage: 9.0.0.
Below is the complete error.

> Exception has occurred.
PlatformException (PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(StorageCipher18Implementation.java:93)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.decodeRawValue(FlutterSecureStorage.java:249)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.read(FlutterSecureStorage.java:69)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:156)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null))

The line is throwing this error is secureStorage.read(key: 'key').

I have tried the below code but still this issue is happening. any news?

> final FlutterSecureStorage storage = const FlutterSecureStorage(
aOptions: AndroidOptions(
encryptedSharedPreferences: true,
),
);

**Comment by juliansteenbakker** [comment]
The error originates from the legacy part of encryptedSharedPreferences, that is being phased out in v10.0.0.

This is what the android docs have to say about it

>    // Note that {@link BadPaddingException} includes {@link AEADBadTagException}.
      // This may happen if the encrypted keyset is corrupted, or if it was encrypted
      // with a different master key. You need to decide how to handle this. You may recover from
      // this by creating a new encrypted keyset, but then you need to delete all data that had
      // been encrypted with the old key.

You can use `resetOnError` which removes all data if such an error occurs.

**Comment by jttuboi** [comment]
> The error originates from the legacy part of encryptedSharedPreferences, that is being phased out in v10.0.0.
> 
> This is what the android docs have to say about it
> 
> > // Note that {[@link](https://github.com/link) BadPaddingException} includes {[@link](https://github.com/link) AEADBadTagException}.
> > // This may happen if the encrypted keyset is corrupted, or if it was encrypted
> > // with a different master key. You need to decide how to handle this. You may recover from
> > // this by creating a new encrypted keyset, but then you need to delete all data that had
> > // been encrypted with the old key.
> 
> You can use `resetOnError` which removes all data if such an error occurs.

any idea when the 10 will be released?

**Comment by hakama99** [comment]
Hello, only customers have reported this issue and I cannot reproduce it. In order to confirm the fix, how do I reproduce it?

**Comment by Den-creator** [comment]
I have the same issue on Samsung.

**Comment by pooja96km** [comment]
Has anyone found a solution?

**Comment by nitipat009** [comment]
@pooja96km are u reproduce or test this issue on 10.0.0-beta.4?

**Comment by SteveJosephh21** [comment]
Has anyone found a solution?

**Comment by moezbaccouche** [comment]
I was able to reproduce this issue on a Samsung S23 Ultra when executing the **read** instruction of **FlutterSecureStorage**.
Upgrading flutter_secure_storage from **9.2.4** to **10.0.0-beta.4** resolves the problem:

```diff
- flutter_secure_storage: ^9.2.4
+ flutter_secure_storage: 10.0.0-beta.4
```

**Comment by juliansteenbakker** [comment]
I have released v10 which should fix this issue. If not, please let me know.

**Comment by Vukan-Levi9** [comment]
@juliansteenbakker I still see this error from Crashlytics with the v10 version.
